version: '3.4'

services:
  GatewayApi:
    image: my-words-gateway
    labels:
      NAME: "Gateway Api"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/project_logs/my-words/gateway:/app/logs" 

    build:
      context: .
      dockerfile: GatewayApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

    restart: always
    ports:
      - "3000:3000"
        
  AuthApi:
    image: my-words-auth
    labels:
      NAME: "Auth Api"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/mnt/project_logs/my-words/auth:/app/logs" 

    build:
      context: .
      dockerfile: AuthApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

    restart: always
    ports:
      - "3001:3001"

##  AssetApi:
##    image: my-words-asset
##    labels:
##      NAME: "Asset Api"
##    volumes:
##      - "/etc/localtime:/etc/localtime:ro"
##      - "/etc/timezone:/etc/timezone:ro"
##      - "/my-words/AssetApi/wwwroot:/app/wwwroot"
##      - "/mnt/project_logs/my-words/asset:/app/logs" 
##
##    build:
##      context: .
##      dockerfile: AssetApi/Dockerfile
##    environment:
##      - ASPNETCORE_ENVIRONMENT=Staging
##
##    restart: always
##    ports:
##      - "3002:3002"

networks:
  happybirthday2you_default:
    external: true
