name: Build and Deploy ASP.NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x' # Yangi versiyaga moslang

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./output --no-restore

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2

  #   - name: Deploy to Server
  #     env:
  #       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #       SSH_HOST: ${{ secrets.SSH_HOST }}
  #       SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  #     run: |
  #       scp -r ./output/* $SSH_USERNAME@$SSH_HOST:/path/to/your/server
  #       ssh $SSH_USERNAME@$SSH_HOST 'sudo systemctl restart your-app-service'
