name: Build and Deploy ASP.NET

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Yangi versiyaga moslang

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./output --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: build # build ishini muvaffaqiyatli tugashini kutadi

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ${{ vars.WORK_DIR }}
          git pull origin master
          docker stop my-words-back-1 || true
          docker rm my-words-back-1 || true
          docker rmi my-words-back || true
          docker compose up -d
